[package]
name = "typ2docx"
version = "0.8.0"
edition = "2024"

[lib]
name = "extract"
path = "extract.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
typst = "0.14"
typst-eval = "0.14"
typst-kit = "0.14"
