[project]
name = "typ2docx"
version = "0.1.0"
dependencies = ["typer"]
requires-python = ">=3.8"

[project.scripts]
typ2docx = "main:app"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
include = [
  "acrobat.applescript",
  "main.py",
  "merge.sh",
  "merge.xslt",
  "preamble.typ",
]
