name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/typ2docx

    steps:
      - uses: actions/checkout@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Build source distribution
        run: uv build --sdist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  generate-lock-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Generate lock file
        run: cargo generate-lockfile

      - name: Append lockfile to release
        uses: softprops/action-gh-release@v2
        with:
          files: Cargo.lock

  deploy-web-app:
    needs: build-and-publish
    runs-on: ubuntu-slim
    steps:
      - name: Trigger rebuild
        run: curl {{ secrets.DEPLOY_HOOK }}
